### ISSUE TITLE
The convolution layers kernel size are set to 3

### ISSUE THREAD

**Issue by W1ndSurf3r** [bionick87/ConvGRUCell-pytorch#3]
Shouldn't the kernel size be equal to kernel_size. It seems to be explicitly assigned to 3. Just commenting because I am using part of your code for a different project, not replicating the paper.

**Comment by bionick87** [comment]
Hey thanks, 

yes, correct. Post the code that you don't understand and please fork my repo as well.

Best,

N

**Comment by W1ndSurf3r** [comment]
Thanks for the response. I ended up using a different repo. I wanted to understand how I can connect the cells and which dimension would correspond to the time steps in a one dimensional GRU where the input is TxF where F are the features and T time-steps. To my understanding so far and with the code, I have written, I am looping over the time-steps to feed the Conv GRU cell and updating hidden state accordingly. 
I forked the repo, if I managed to integrate that with your code and it's correct what I am doing :smile: , ill post here. It will be a useful extension for people like me.
